# This rule is not used by the project workload-schedule-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to infra.illumin.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workload-schedule-operator
    app.kubernetes.io/managed-by: kustomize
  name: workloadschedule-viewer-role
rules:
- apiGroups:
  - infra.illumin.com
  resources:
  - workloadschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.illumin.com
  resources:
  - workloadschedules/status
  verbs:
  - get
